package frames

import (
	"fmt"

	pipelineframes "github.com/weedge/pipeline-go/pkg/frames"

	"achatbot/pkg/types"
)

// VADStateAudioRawFrame represents a VAD state audio frame
type VADStateAudioRawFrame struct {
	*pipelineframes.AudioRawFrame

	State    types.VADState `json:"state"`
	SpeechID int            `json:"speech_id"`
	IsFinal  bool           `json:"is_final"`
	StartAtS float64        `json:"start_at_s"`
	CurAtS   float64        `json:"cur_at_s"`
	EndAtS   float64        `json:"end_at_s"`
}

// NewVADStateAudioRawFrame creates a new VADStateAudioRawFrame with default values
func NewVADStateAudioRawFrame() *VADStateAudioRawFrame {
	return &VADStateAudioRawFrame{
		State:    types.Quiet,
		SpeechID: 0,
		IsFinal:  false,
		StartAtS: 0.0,
		CurAtS:   0.0,
		EndAtS:   0.0,
	}
}

// String implements string representation of VADStateAudioRawFrame
func (f *VADStateAudioRawFrame) String() string {
	return fmt.Sprintf("%s (state: %v speech_id: %d is_final: %t start_at_s: %.2f cur_at_s: %.2f end_at_s: %.2f)",
		f.AudioRawFrame.String(),
		f.State,
		f.SpeechID,
		f.IsFinal,
		f.StartAtS,
		f.CurAtS,
		f.EndAtS,
	)
}

// SpriteFrame represents a sprite frame (collection of images)
type SpriteFrame struct {
	*pipelineframes.DataFrame
	Images []*pipelineframes.ImageRawFrame
}

// NewSpriteFrame creates a new SpriteFrame
func NewSpriteFrame(images []*pipelineframes.ImageRawFrame) *SpriteFrame {
	return &SpriteFrame{
		DataFrame: pipelineframes.NewDataFrameWithName("SpriteFrame"),
		Images:    images,
	}
}

// AnimationAudioRawFrame represents an animation audio frame
type AnimationAudioRawFrame struct {
	*pipelineframes.AudioRawFrame
	AnimationJSON string `json:"animation_json"`
	AvatarStatus  string `json:"avatar_status"`
}

// NewAnimationAudioRawFrame creates a new AnimationAudioRawFrame
func NewAnimationAudioRawFrame(audio []byte, sampleRate, numChannels, sampleWidth int, animationJSON, avatarStatus string) *AnimationAudioRawFrame {
	return &AnimationAudioRawFrame{
		AudioRawFrame: pipelineframes.NewAudioRawFrame(audio, sampleRate, numChannels, sampleWidth),
		AnimationJSON: animationJSON,
		AvatarStatus:  avatarStatus,
	}
}

// String implements string representation of AnimationAudioRawFrame
func (f *AnimationAudioRawFrame) String() string {
	return fmt.Sprintf("%s animation_json: %s avatar_status: %s",
		f.AudioRawFrame.String(),
		f.AnimationJSON,
		f.AvatarStatus)
}

// TransportMessageFrame represents a transport message frame
type TransportMessageFrame struct {
	*pipelineframes.DataFrame
	Message []byte
}

// NewTransportMessageFrame creates a new TransportMessageFrame
func NewTransportMessageFrame(message []byte) *TransportMessageFrame {
	return &TransportMessageFrame{
		DataFrame: pipelineframes.NewDataFrameWithName("TransportMessageFrame"),
		Message:   message,
	}
}

type PathAudioRawFrame struct {
	*pipelineframes.AudioRawFrame
	Path string `json:"path"`
}

// NewPathAudioRawFrame creates a new PathAudioRawFrame
func NewPathAudioRawFrame(audio []byte, sampleRate, numChannels, sampleWidth int, path string) *PathAudioRawFrame {
	return &PathAudioRawFrame{
		AudioRawFrame: pipelineframes.NewAudioRawFrame(audio, sampleRate, numChannels, sampleWidth),
		Path:          path,
	}
}

// String implements string representation of PathAudioRawFrame
func (f *PathAudioRawFrame) String() string {
	return fmt.Sprintf("%s path: %s", f.AudioRawFrame.String(), f.Path)
}

type ThinkTextFrame struct {
	*pipelineframes.TextFrame
	ThinkStartTag string `json:"think_start_tag"`
	ThinkEndTag   string `json:"think_end_tag"`
}

// NewThinkTextFrame creates a new ThinkTextFrame
func NewThinkTextFrame(text string) *ThinkTextFrame {
	return &ThinkTextFrame{
		TextFrame:     pipelineframes.NewTextFrame(text),
		ThinkStartTag: "<think>",
		ThinkEndTag:   "</think>",
	}
}

func (f *ThinkTextFrame) String() string {
	return fmt.Sprintf("%s think_start_tag: %s think_end_tag: %s", f.TextFrame.String(), f.ThinkStartTag, f.ThinkEndTag)
}

// FunctionCallFrame represents a function call frame generated by LLM
type FunctionCallFrame struct {
	*pipelineframes.DataFrame
	ToolCallID   string         `json:"tool_call_id"`
	FunctionName string         `json:"function_name"`
	Arguments    map[string]any `json:"arguments"`
	Index        int            `json:"index"`
	Type         string         `json:"type"`
}

// NewFunctionCallFrame creates a new FunctionCallFrame
func NewFunctionCallFrame(toolCallID, functionName string, arguments map[string]any, index int) *FunctionCallFrame {
	return &FunctionCallFrame{
		DataFrame:    pipelineframes.NewDataFrameWithName("FunctionCallFrame"),
		ToolCallID:   toolCallID,
		FunctionName: functionName,
		Arguments:    arguments,
		Index:        index,
		Type:         "function",
	}
}

// String implements string representation of FunctionCallFrame
func (f *FunctionCallFrame) String() string {
	return fmt.Sprintf("%s(function_name: %s, tool_call_id: %s, arguments: %+v index: %d type: %s)",
		f.DataFrame.Name(), f.FunctionName, f.ToolCallID, f.Arguments, f.Index, f.Type)
}
